# camera parameters for src/gnm_locobot.launch
video_device: "/dev/video0" # change this to your video device path
image_width: 1600 
image_height: 1200 
pixel_format: yuyv
camera_frame_id: "usb_cam"
io_method: "mmap"
framerate: 9