name: vint_deployment
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.
  - torchvision
  - numpy
  - matplotlib
  - pyyaml
  - rospkg
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - einops
      - vit-pytorch
      - efficientnet_pytorch
      - warmup_scheduler
      - diffusers==0.11.1